spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          # trailing slash is important!
          issuer-uri: https://dev-tt4we0ft.us.auth0.com/
  h2:
    console:
      enabled: true
auth0:
  audience: chess-api
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:file:./database/developmentDb
    username: sa
    driverClassName: org.h2.Driver
webclient:
  url: http://localhost:3000
---
spring:
  config:
    activate:
      on-profile: beta
  datasource:
    url: jdbc:h2:file:./database/betaDb
    username: sa
    password: foobarbaz
    driverClassName: org.h2.Driver
server:
  port: 8099
webclient:
  url: https://kingsfolly-beta.ngrok.io


