spring:
  config:
    import: secrets.yml
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          # trailing slash is important!
          issuer-uri: https://dev-tt4we0ft.us.auth0.com/
auth0:
  audience: chess-api

